# Generated by Powerlevel10k configuration wizard.
# MODIFIED: colours come from the theme bundle (~/dotfiles/theme), see below.

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'
  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  #
  # --=( Theme colours )=--
  # From the bundle ~/.config/theme/current/shell.zsh, sourced by .zshrc before
  # this file; sourced here too in case this file is loaded on its own.
  [[ -n "${THEME_LIME:-}" ]] || source ~/.config/theme/current/shell.zsh 2>/dev/null || source ~/dotfiles/theme/build/voidrunner/shell.zsh 2>/dev/null
  local theme_fg="$THEME_FG"
  local theme_lime="$THEME_LIME"
  local theme_mint="$THEME_MINT"
  local theme_lav="$THEME_LAV"
  local theme_sky="$THEME_SKY"
  local theme_rose="$THEME_ROSE"
  local theme_red="$THEME_RED"
  local theme_dim="$THEME_DIM"
  # -------------------------------------------------------------------

  # This makes the prompt appear on a new line.
  typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=true

  # ADDED "shortvix" to the left prompt elements.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon dir vcs
  )
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status command_execution_time background_jobs direnv asdf virtualenv time
  )

  typeset -g POWERLEVEL9K_MODE=nerdfont-v3
  typeset -g POWERLEVEL9K_ICON_PADDING=moderate

  # Prompt symbol for the new line
  typeset -g POWERLEVEL9K_PROMPT_CHAR_SYMBOL="%F{$theme_lime}❯%f"
  
  # Separators and line endings
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=' '
  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=' '
  
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX=''
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX=''
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX=''

  ################################[ os_icon: os identifier ]##################################
  # CHANGED the icon to a new symbol and kept the color lavender.
  #
  # This used to be the literal string '󰣇 shortVIX93'. Because .p10k.zsh is
  # shared across every machine, that meant an ssh session on a work server looked
  # identical to the desktop — easy to run the wrong command on the wrong host.
  # Keep the handle on the desktop; show the real hostname everywhere else. Same
  # colour on both since 2026-09-25 (Laurent's call): the label, not the colour,
  # is what tells the desktop from a remote box now.
  if [[ "${(%):-%m}" == "laurent-dell-desktop" ]]; then
    typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION='󰣇 shortVIX93'
    typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND="$theme_rose"
  else
    typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION='󰣇 %m'
    typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND="$theme_rose"
  fi
  typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=''

  ##################################[ dir: current directory ]##################################
  typeset -g POWERLEVEL9K_DIR_BACKGROUND=''
  typeset -g POWERLEVEL9K_DIR_FOREGROUND="$theme_lime"
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND="$theme_lime"
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND="$theme_lime"
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
  typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=80
  local anchor_files=(.git .svn .hg)
  typeset -g POWERLEVEL9K_SHORTEN_FOLDER_MARKER="(${(j:|:)anchor_files})"
  typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=v3

  ####################################[ vcs: git status ]######################################
  typeset -g POWERLEVEL9K_VCS_BACKGROUND=''
  typeset -g POWERLEVEL9K_VCS_FOREGROUND="$theme_mint"
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND="$theme_mint"
  typeset -g POWERLEVEL9K_VCS_STAGED_FOREGROUND="$theme_lav"
  typeset -g POWERLEVEL9K_VCS_UNSTAGED_FOREGROUND="$theme_red"
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="$theme_mint"
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND="$theme_red"
  typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_COLOR="$theme_mint"
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
  typeset -g POWERLEVEL9K_VCS_BACKENDS=(git)
  typeset -g POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN='~'

  ##########################[ status: exit code of the last command ]###########################
  typeset -g POWERLEVEL9K_STATUS_OK=false
  typeset -g POWERLEVEL9K_STATUS_ERROR=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='✘'
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND="$theme_red"
  typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=''

  ###################[ command_execution_time: duration of the last command ]###################
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="$theme_lime"
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=''
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3

  #######################[ background_jobs: presence of background jobs ]#######################
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND="$theme_lime"
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=''
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false

  #######################[ direnv: direnv status (https://direnv.net/) ]########################
  typeset -g POWERLEVEL9K_DIRENV_FOREGROUND="$theme_lime"
  typeset -g POWERLEVEL9K_DIRENV_BACKGROUND=''

  ###############[ asdf: asdf version manager (https://github.com/asdf-vm/asdf) ]###############
  typeset -g POWERLEVEL9K_ASDF_FOREGROUND="$theme_lime"
  typeset -g POWERLEVEL9K_ASDF_BACKGROUND=''
  typeset -g POWERLEVEL9K_ASDF_PROMPT_ALWAYS_SHOW=false

  ###[ virtualenv: python virtual environment ]###
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND="$theme_lime"
  typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=''
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
  typeset -g POWERLEVEL9K_VIRTUALENV_{LEFT,RIGHT}_DELIMITER=''

  ####################################[ time: current time ]####################################
  typeset -g POWERLEVEL9K_TIME_FOREGROUND="$theme_lime"
  typeset -g POWERLEVEL9K_TIME_BACKGROUND=''
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'

  # Transient prompt and instant prompt settings.
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  (( ! $+functions[p10k] )) || p10k reload
}
# Tell `p10k configure` which file it should overwrite.
typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
